-- https://docs.google.com/document/d/1GS_D8wfch_i43DAkl8M1abod3slHmq41Ss-FOh3Pg5o/edit


CREATE TABLE companies (
  id serial PRIMARY KEY,
  info JSON
}

ALTER TABLE companies

ADD COLUMN company_name TEXT,
ADD COLUMN company_number VARCHAR (200),
ADD COLUMN contact_name VARCHAR (200),
ADD COLUMN contact_role VARCHAR (200),
ADD COLUMN contact_phone VARCHAR (200),
ADD COLUMN contact_email VARCHAR (200),

ADD COLUMN ventilator_production VARCHAR (5),
ADD COLUMN ventilator_parts_human VARCHAR (5),
ADD COLUMN ventilator_parts_veterinary VARCHAR (5),
ADD COLUMN ventilator_parts_any VARCHAR (5),
ADD COLUMN ventilator_parts_details TEXT,

ADD COLUMN air_compressors_design VARCHAR (5),
ADD COLUMN bellows_design VARCHAR (5),
ADD COLUMN self_inflating_bags_design VARCHAR (5),
ADD COLUMN gas_mixing_valves_design VARCHAR (5),
ADD COLUMN pressure_regulators_design VARCHAR (5),
ADD COLUMN flow_control_valves_design VARCHAR (5),
ADD COLUMN solenoid_valves_design VARCHAR (5),
ADD COLUMN pressure_relief_valves_design VARCHAR (5),
ADD COLUMN check_valves_design VARCHAR (5),
ADD COLUMN industrial_automation_components_design VARCHAR (5),
ADD COLUMN power_supplies_design VARCHAR (5),
ADD COLUMN electric_motors_design VARCHAR (5),
ADD COLUMN linear_actuators_design VARCHAR (5),
ADD COLUMN tubing_design VARCHAR (5),
ADD COLUMN pressure_sensors_design VARCHAR (5),
ADD COLUMN oxygen_sensors_design VARCHAR (5),
ADD COLUMN flow_sensors_design VARCHAR (5),
ADD COLUMN manometers_design VARCHAR (5),
ADD COLUMN heat_design VARCHAR (5),
ADD COLUMN air_filter_design VARCHAR (5),

ADD COLUMN air_compressors_manufacture VARCHAR (5),
ADD COLUMN bellows_manufacture VARCHAR (5),
ADD COLUMN self_inflating_bags_manufacture VARCHAR (5),
ADD COLUMN gas_mixing_valves_manufacture VARCHAR (5),
ADD COLUMN pressure_regulators_manufacture VARCHAR (5),
ADD COLUMN flow_control_valves_manufacture VARCHAR (5),
ADD COLUMN solenoid_valves_manufacture VARCHAR (5),
ADD COLUMN pressure_relief_valves_manufacture VARCHAR (5),
ADD COLUMN check_valves_manufacture VARCHAR (5),
ADD COLUMN industrial_automation_components_manufacture VARCHAR (5),
ADD COLUMN power_supplies_manufacture VARCHAR (5),
ADD COLUMN electric_motors_manufacture VARCHAR (5),
ADD COLUMN linear_actuators_manufacture VARCHAR (5),
ADD COLUMN tubing_manufacture VARCHAR (5),
ADD COLUMN pressure_sensors_manufacture VARCHAR (5),
ADD COLUMN oxygen_sensors_manufacture VARCHAR (5),
ADD COLUMN flow_sensors_manufacture VARCHAR (5),
ADD COLUMN manometers_manufacture VARCHAR (5),
ADD COLUMN heat_manufacture VARCHAR (5),
ADD COLUMN air_filter_manufacture VARCHAR (5),

ADD COLUMN air_compressors_supply VARCHAR (5),
ADD COLUMN bellows_supply VARCHAR (5),
ADD COLUMN self_inflating_bags_supply VARCHAR (5),
ADD COLUMN gas_mixing_valves_supply VARCHAR (5),
ADD COLUMN pressure_regulators_supply VARCHAR (5),
ADD COLUMN flow_control_valves_supply VARCHAR (5),
ADD COLUMN solenoid_valves_supply VARCHAR (5),
ADD COLUMN pressure_relief_valves_supply VARCHAR (5),
ADD COLUMN check_valves_supply VARCHAR (5),
ADD COLUMN industrial_automation_components_supply VARCHAR (5),
ADD COLUMN power_supplies_supply VARCHAR (5),
ADD COLUMN electric_motors_supply VARCHAR (5),
ADD COLUMN linear_actuators_supply VARCHAR (5),
ADD COLUMN tubing_supply VARCHAR (5),
ADD COLUMN pressure_sensors_supply VARCHAR (5),
ADD COLUMN oxygen_sensors_supply VARCHAR (5),
ADD COLUMN flow_sensors_supply VARCHAR (5),
ADD COLUMN manometers_supply VARCHAR (5),
ADD COLUMN heat_supply VARCHAR (5),
ADD COLUMN air_filter_supply VARCHAR (5),

ADD COLUMN air_compressors_location VARCHAR (5),
ADD COLUMN bellows_location VARCHAR (5),
ADD COLUMN self_inflating_bags_location VARCHAR (5),
ADD COLUMN gas_mixing_valves_location VARCHAR (5),
ADD COLUMN pressure_regulators_location VARCHAR (5),
ADD COLUMN flow_control_valves_location VARCHAR (5),
ADD COLUMN solenoid_valves_location VARCHAR (5),
ADD COLUMN pressure_relief_valves_location VARCHAR (5),
ADD COLUMN check_valves_location VARCHAR (5),
ADD COLUMN industrial_automation_components_location VARCHAR (5),
ADD COLUMN power_supplies_location VARCHAR (5),
ADD COLUMN electric_motors_location VARCHAR (5),
ADD COLUMN linear_actuators_location VARCHAR (5),
ADD COLUMN tubing_location VARCHAR (5),
ADD COLUMN pressure_sensors_location VARCHAR (5),
ADD COLUMN oxygen_sensors_location VARCHAR (5),
ADD COLUMN flow_sensors_location VARCHAR (5),
ADD COLUMN manometers_location VARCHAR (5),
ADD COLUMN heat_location VARCHAR (5),
ADD COLUMN air_filter_location VARCHAR (5),

ADD COLUMN offer_organisation TEXT,

ADD COLUMN design_skills VARCHAR (5),
ADD COLUMN rapid_prototyping_skills VARCHAR (5),
ADD COLUMN manufacturing_manual_skills VARCHAR (5),
ADD COLUMN manufacturing_automated_skills VARCHAR (5),
ADD COLUMN machine_shops_skills VARCHAR (5),
ADD COLUMN pneumatic_part_manufacturers_skills VARCHAR (5),
ADD COLUMN contract_skills VARCHAR (5),
ADD COLUMN certification_skills VARCHAR (5),
ADD COLUMN logistics_skills VARCHAR (5),
ADD COLUMN medical_training_skills VARCHAR (5),

ADD COLUMN design_specialism VARCHAR (5),
ADD COLUMN rapid_prototyping_specialism VARCHAR (5),
ADD COLUMN manufacturing_manual_specialism VARCHAR (5),
ADD COLUMN manufacturing_automated_specialism VARCHAR (5),
ADD COLUMN machine_shops_specialism VARCHAR (5),
ADD COLUMN pneumatic_part_manufacturers_specialism VARCHAR (5),
ADD COLUMN contract_specialism VARCHAR (5),
ADD COLUMN certification_specialism VARCHAR (5),
ADD COLUMN logistics_specialism VARCHAR (5),
ADD COLUMN medical_training_specialism VARCHAR (5),

ADD COLUMN design_location VARCHAR (20),
ADD COLUMN rapid_prototyping_location VARCHAR (20),
ADD COLUMN manufacturing_manual_location VARCHAR (20),
ADD COLUMN manufacturing_automated_location VARCHAR (20),
ADD COLUMN machine_shops_location VARCHAR (20),
ADD COLUMN pneumatic_part_manufacturers_location VARCHAR (20),
ADD COLUMN contract_location VARCHAR (20),
ADD COLUMN certification_location VARCHAR (20),
ADD COLUMN logistics_location VARCHAR (20),
ADD COLUMN medical_training_location VARCHAR (20),

ADD COLUMN resources_space VARCHAR(20),
ADD COLUMN resources_equipment VARCHAR(20),
ADD COLUMN resources_personnel VARCHAR(20),
ADD COLUMN resources_other VARCHAR(20),
ADD COLUMN resource_details TEXT,

ADD COLUMN created_at TIMESTAMP DEFAULT now();

